// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalApp.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string LicenseNumber { get; set; }

    public string Username { get; set; }

    public string Pwd { get; set; }

    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();
}