//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.BorrowTransactions = new HashSet<BorrowTransaction>();
        }
        public int MemberID { get; set; }

        [Required(ErrorMessage = "Please enter Username")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Username must be alphabets only")]
        public string uname { get; set; }

        [Required(ErrorMessage = "Please enter Password")]
        [RegularExpression(@"^(?=.*[A-Z])(?=.*[\W])[a-zA-Z0-9\W]{5,}$", ErrorMessage = "Invalid password")]
        public string pwd { get; set; }

        [Required(ErrorMessage = "Please enter Full Name")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Full Name must contain only letters and spaces.")]
        public string FullName { get; set; }

        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "email should be in proper format")] 
        public string Email { get; set; }

       
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone number must be 10 digits.")]
        public string Phone { get; set; }

        public System.DateTime JoinDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowTransaction> BorrowTransactions { get; set; }
    }
}
