//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [Display(Name = "Product ID")]
        [Required(ErrorMessage ="please enter pid")]
        [RegularExpression(@"^p[0-9]{3}$", ErrorMessage = "Invalid format")]
        public string pid { get; set; }

        [Display(Name = "Product Name")]
        [Required(ErrorMessage = "please enter pname")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Name must contain only letters and spaces.")]
        public string pname { get; set; }

        [Display(Name = "Product Description")]
        [StringLength(10,ErrorMessage ="only 10 characters alllowed")]
        public string description { get; set; }

        [Display(Name = "Product Price")]
        [Required(ErrorMessage = "please enter price")]
        [Range(1000, 10000, ErrorMessage = "Invalid Range")]
        public Nullable<int> price { get; set; }

        [Display(Name = "Product Image")]
        [FileExtensions(Extensions = "jpg", ErrorMessage = "Please upload a valid image file (jpg).")]
        public string pimage { get; set; }
    }
}
