//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoredProceduresDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderid { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string orderlocation { get; set; }
        public string productname { get; set; }
        public Nullable<int> custid { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual customer1 customer { get; set; }
        public virtual customer1 customer1 { get; set; }
    }
}
